# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJBactga4rIGE7i_4020yzuwODyjP-zs
"""

from google.colab import files

uploaded = files.upload()

import zipfile
import io

# Get the uploaded file name
zip_file = list(uploaded.keys())[0]

# Extract the ZIP file
with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall()
    file_list = zip_ref.namelist()

print("Extracted files:", file_list)

import pandas as pd

# Assuming there’s one CSV file inside the ZIP
csv_file = [f for f in file_list if f.endswith('.csv')][0]

# Load the CSV
df = pd.read_csv(csv_file)
df.head()  # Show first few rows

summary = df.describe().T  # Transpose for readability
summary['median'] = df.median(numeric_only=True)
summary

import pandas as pd
import matplotlib.pyplot as plt

numeric_cols = df.select_dtypes(include='number').columns.tolist()

""".Create histograms and boxplots for numeric features.

"""

for col in numeric_cols:
    # Histogram
    plt.figure()
    df[col].plot(kind='hist', bins=30, edgecolor='black')
    plt.title(f'Histogram of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()

    # Boxplot
    plt.figure()
    df.boxplot(column=col, vert=False)
    plt.title(f'Boxplot of {col}')
    plt.xlabel(col)
    plt.grid(True)
    plt.show()

""".Use pairplot/correlation matrix for feature relationships

"""

!pip install seaborn --quiet

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

numeric_cols = df.select_dtypes(include='number').columns.tolist()

# Compute correlation matrix
corr = df[numeric_cols].corr()

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlation Matrix Heatmap")
plt.show()

